# 官方文档
# https://v2raya.org/docs/prologue/introduction

---
version: "3"
# 最后编辑时间：2026-08-31
services:
  v2raya:
    image: ghcr.io/workroom2008/v2raya-hb:latest
    # 镜像地址
    container_name: v2raya
    # 容器名字
    hostname: v2raya
    # 主机名
    privileged: true
    # 特权模式，赋予容器几乎与主机相同的权限
    volumes:
      - /volume1/docker/v2raya/v2raya:/etc/v2raya
      # 配置文件
    # network_mode: bridge
    network_mode: host
    # host模式需要容器内的端口不被占用，不需要端口映射，后续端口映射全都开头加#注释掉，否则注释掉这条
    # ports:
      # - 2017:2017/tcp
      # WebUI 端口
      # - 20170:20170/tcp
      # sock代理端口
      # - 20171:20171/tcp
      # http代理端口
      # - 20172:20172/tcp
      # https代理端口
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
